@url = http://localhost:5000

@reservationId= 8b3abc9b-95e5-4344-a4a2-735c3b340732

@parkingSpotId = 00000000-0000-0000-0000-000000000001
###
GET  {{url}}/reservations

###
GET  {{url}}/reservations/{{reservationId}}

###
POST  {{url}}/reservations/vehicle
Content-Type: application/json

{
    "parkingSpotId": "{{parkingSpotId}}",
    "capacity":1,
    "employeeName": "Mark Doe",
    "licensePlate": "XYZ124",
    "Date" : "2024-02-23"
}

###
POST  {{url}}/reservations/cleaning
Content-Type: application/json

{
    "Date" : "2024-02-23"
}

###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json

{
    "licensePlate":"XYZ123"
}

###
DELETE {{url}}/reservations/{{reservationId}}