@url = http://localhost:5000

@reservationId= 3cf8ba1a-f8d1-4b19-8cb8-07efd8c96602

@parkingSpotId = 00000000-0000-0000-0000-000000000001
###
GET  {{url}}/reservations

###
GET  {{url}}/reservations/{{reservationId}}

###
POST  {{url}}/reservations
Content-Type: application/json

{
    "parkingSpotId": "{{parkingSpotId}}",
    "employeeName": "John Doe",
    "licensePlate": "XYZ124",
    "Date" : "2024-01-21"
}

###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json

{
    "licensePlate":"XYZ123"
}

###
DELETE {{url}}/reservations/{{reservationId}}